### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by gcstaublin** [gcstaublin/pregame#3]
Let's talk about variables.

1. How do we organize them? One big file vs. smaller, discrete files (i.e. `settings.colors`, `settings.zindex`, etc)
1. What is the naming convention?  
  - Underscores vs. hyphens: `$ui_text_dark_color` vs `$ui-text-dark-color`
  - Any BEM style modifications? `$ui-text-color--dark`  
  - Order of the naming convention? 
1. Do we have configuration (local) variables on the top of individual files?  
For instance, does the button mixin file have the local default variables declared at the top of the that file, mapping back to our universally declared variables?
1. Using `!default` variables?  
Hypothetically, we could allow for some configuration by adding the default flag to certain variables, which could then be overwritten locally by a cluster importing a `defaults.scss` file before the rest of Pregame

**Comment by gcstaublin** [comment]
For arguments sake, here is an abbreviated settings.color file from a recent project.

This isn't an editorial comment, rather an illustration of how I've approached this.


```
// --------------------------------------------
// --------------------------------------------
//
// Colors
//
// --------------------------------------------
// --------------------------------------------


// Named Colors
// --------------------------------------------

// grayscale
$color--black:         #000000;
$color:                $color--black;
$color--white:         #ffffff;
$color--cream:         #eeeae9;
$color--gray-5:        #5d606a;
$color--gray-6:        #6d717d;
$color--gray-7:        #7e8495;
$color--gray-9:        #9ca0a9;
$color--gray-c:        #c7c8ca;
$color--gray-e4:       #e4e4ec;
$color--gray-f4:       #f4f3fc;
$color--gray-fb:       #fbfbfe;
$color--gray-b7:       #b7bdc7;

// colors
$color--avocado:       #92dd75;
$color--green:         #1f9d50;
$color--blue-green:    #64c59c;
$color--sage:           #8bc59c;
$color--aqua:          #5cbdb6;
$color--chartreuse:    #cff14c;
$color--dark-chartreuse: darken($color--chartreuse, 15%);
$color--bright-green:  #b4de11;
$color--yellow:        #fbfa59;
$color--red:           #f3423b;
$color--pink:          #f99cc1;
$color--slate:         #45506b;
$color--navy:          #1f3159;
$color--dark-slate:    #2f3046;
$color--midnight:      #1d2424;
$color--robins-egg:    #a9e1ea;
$color--lilac:         #8d9ddd;



// Brand
// --------------------------------------------
$color-brand--main:     $color--green;
$color-brand--main--lt: $color--blue-green;


// Body and Mods Backgrounds
// --------------------------------------------
$color-bg--default:       $color--gray-f4;
$color-bg--landing:       $color--gray-f4;
$color-bg--body:          $color--white;
$color-bg--dark:          $color--dark-slate; // used on book pages. look at a background-image
$color-bg--footer:        $color--dark-slate;
$color-bg--footer--promo: lighten($color--dark-slate, 3%);


// Page Header Backgrounds
// --------------------------------------------
$color-page-header:      $color-brand--main--lt;


// Page Mod Backgrounds
// --------------------------------------------
$color-bg--mod:               $color--gray-f4;
$color-bg--promo:             linear-gradient(90deg, #F0DA56, #F8AA44);


// Book Modal Backgrounds
// --------------------------------------------
$color-bg--modal:             $color--white;


// Social
// --------------------------------------------
$color-bg--social:            $color-bg--default;
$color-text--social:          #6b717d;
$color-text--social--drk:     darken($color-text--social, 20%);


// Headlines
// --------------------------------------------
$color-head--accent:          #1d9d4f;
$color-head--xdrk:            #000;
$color-head--drk:             #1d2323;
$color-head--lt:              #7f7f7f;
$color-book--drk:             #45516A;
$color-book--med:             lighten($color-book--drk, 7%);
$color-book--lt:              #7f7f7f;
$color-author-title:          $color--slate;


// Promo
// --------------------------------------------
$color-promo--text:           #255EA7;


// Text
// --------------------------------------------
$color-text:                  $color--dark-slate;
$color-text--head:            $color--dark-slate;
$color-text--subhead:         $color--gray-9;
$color-text--article:         $color--gray-5;
$color-text--caption:         $color--gray-7;


// Footer
$color-text--footer--lt:      lighten($color--gray-6, 10%);
$color-text--footer--med:     $color--gray-6;
$color-text--footer--dark:    $color--slate;
$color-text--footer--input:   $color--white;
$color-text--footer--link:    $color-text--footer--lt;
$color-text--footer--social:  $color--gray-c;


// Teases
// --------------------------------------------
$color-tz--cat:         $color-brand--main;
$color-tz--text:        $color-text;
$color-tz--head:        $color--dark-slate;
$color-tz--head--hp:    $color--slate;
$color-tz--fade:        linear-gradient(-180deg, rgba(255, 255, 255, 0) 50%, rgba(255, 255, 255, 0.9) 100% );


// Book Header
// --------------------------------------------
$color-hdr--accent:     $color--dark-slate;


// Recipes
// --------------------------------------------
$color-recipe-head--accent: $color-brand--main;
$color-recipe-head--dark:   black;
$color-recipe-text:         $color-text;

// Tables
// --------------------------------------------
$color-table-border:         $color--gray-e4;
$color-table-head:           $color-text;
$color-table-head-bg:        $color--gray-f4;
$color-table-caption:        $color--gray-9;
$color-table-th-border:      $color--gray-c;
$color-table-td-border:      $color--gray-c;
$color-table-stripes:        lighten($color--gray-f4, 1%);



// Palettes
// --------------------------------------------

// These names map directly to the palette names below
// So, yes, you need to add a theme name to both lists
$names: juniper,
        lemongrass,
        lilac,
        tomatoes,
        piggy,
        bluefin,
        charcoal,
        robin,
        saffron,
        espresso,
        raspberries,
        avocados;


$themes: (
  juniper: (
    // Nav
    nav-link:    #0b3a6b,
    search:      #0b3a6b,

    // More Dropdown
    more-bg:     #a7e0ea,
    more-h:      #0b3a6b,
    more-link:   #0b3a6b,
    more-close:  #0b3a6b,

    // Page Header
    pg-hdr-bg:   #a7e0ea,
    pg-hdr-h:    #ffffff,
    pg-hdr-text: #0b3a6b,
    img-bdr:     #a7e0ea,

    // Media
    media-bg:    #0b3a6b,
    media-h:     #ffffff,
    media-bdr:   #0b3a6b,

    // Reviews
    rvw-bg:      #a7e0ea,
    rvw-h:       #0b3a6b,
    rvw-dec-bg:  #0b3a6b,
    rvw-dec:     #a7e0ea,
    rvw-bdr:     #0b3a6b,

    // Modal
    mdl-bg:      #a7e0ea,
    mdl-h:       #FFFFFF,
    mdl-text:    #0b3a6b,
    mdl-link:    #0b3a6b,

    // Base
    bdr:         #0b3a6b,
    bg-main:     #a7e0ea,
    bg-alt:      #f4f3fc,
    bg-btn:      #0b3a6b,
    btn-text:    #ffffff,
    btn-arrow:   #a7e0ea,
    link-hdr:    #088946,
    link-text:   #0b3a6b,
    label-btn:   #ffffff,
    hdr-text:    #0b3a6b,
    hdr-h:       #0b3a6b,
    hdr-logo:    #a7e0ea,
  ),
  piggy: (
    // Nav
    nav-link:    #f99cc1,
    search:      #f99cc1,

    // More Dropdown
    more-bg:     #f9c5d6,
    more-h:      #f4f3fc,
    more-link:   #6d717d,
    more-close:  #f4f3fc,

    // Page Header
    pg-hdr-bg:   #f9c5d6,
    pg-hdr-h:    #f4f3fc,
    pg-hdr-text: #6d717d,
    img-bdr:     #f9c5d6,
    hdr-price:   #6d717d,

    // Media
    media-bg:    #6d717d,
    media-h:     #f4f3fc,
    media-bdr:   #6d717d,

    // Reviews
    rvw-bg:      #f9c5d6,
    rvw-h:       #f4f3fc,
    rvw-dec-bg:  #f99cc1,
    rvw-dec:     #f9c5d6,
    rvw-bdr:     #f9c5d6,

    // Modal
    mdl-bg:      #f9c5d6,
    mdl-h:       #f4f3fc,
    mdl-text:    #6d717d,
    mdl-link:    #f99cc1,

    // Base
    bdr:         #6d717d,
    bg-main:     #f9c5d6,
    bg-alt:      #f4f3fc,
    bg-btn:      #f99cc1,
    btn-text:    #f4f3fc,
    btn-arrow:   #f9c5d6,
    link-hdr:    #2f3046,
    link-text:   #f99cc1,
    label-btn:   #ffffff,
    hdr-text:    #6d717d,
    hdr-h:       #f99cc1,
    hdr-logo:    #f9c5d6,
  )

);

```

**Comment by mfouquet** [comment]
1. My vote is for separate files. I was thinking originally just one file, but we'll probably end up having a lot and if we separate them out mixins, we should do the same with variables. Set up the expectation and all that. Using Atom/Sublime you can pretty quickly navigate between files. 
2. Ever since Nick showed me the light, I like the underscores because it's easier to copy/paste. I don't know how to feel about the BEM style naming - my gut says no since I like the underscores. I could see the argument though for local variables (like for buttons) since those won't be copied/used elsewhere except within that element and you'll run into more times where you'd need modifiers. 
3. I think I know the benefits of doing this and I'm not sure I'm completely sold on it - what do you see this solving?
4. Same as 3.

**Comment by nick-adams** [comment]
Regarding organization:

What if... Imagine a world...

We had global variables, _and_ local variables, for lack of a better word.

Global variables are basically configurations that apply the to the entire library. Maybe they live in a _globals.scss, or a _configs.scss file.

Local variables are specific to the component  or elements. So they would be at the top of the _typography.scss file, or the top of the _modal.scss file. 

That gives things context where you always know to find a variable that affects this specific thing, the variable is in that same partial as it's styles. This is in keeping with the component way of thinking.

You could also extend this thinking to mixins. A global type mixin, and then local ones. A mixin that drives a button should be found right in _buttons.scss.

Thoughts? It's just a different way of thinking and grouping. Trying to think about what is easier to grasp as a new person to the codebase...

**Comment by mfouquet** [comment]
I think that's what Grant has going on right now in pregame here. There's files for `colors` and `transitions` but then the `buttons` file has the local variables and mixins that are solely for the use of the buttons. 

One small annoyance with SASS is that all variables are global unless scoped with brackets in something like a mixin. So that slightly ruins the effect we're going with but should be OK as long as we keep an eye on it.

**Comment by gcstaublin** [comment]
Since I've started with separate files, we'll keep going with that. We can always copy and paste into a separate master file, if needed.

For underscores in variable naming, I feel like I don't understand the value or what problem that solves. Because CSS is a hyphen delimited language, `font-size`, `background-color`, etc, a naming system that matches the language. However, if you guys have me backed into a corner with no hope for escape, I could change my mind.

I am currently running with a global/local setup, much like the world you describe @nick-adams . One could argue that it just creates an additional abstraction; that one has to open yet another file to see what value is being passed. However, the localized variables make sense in my mind, as it offers smaller, more discrete configuration. 

The opportunity the localized variables create is using the `!default` flag. This might only come in handy if and/or when we open source our library for others to use. Here's an example how that might work.

Inside `_buttons.scss` we have:
`sweet-button-color: red !default;`

Then inside `_settings-overrides.scss` we have:
`sweet-button-color: blue;`

The Override file is imported before our `_buttons.scss` file

So imagine that `pregame.scss` is the master manifest that imports all of the library. The import would look like this:

```
@import _setting-overrrides;
@import pregame;
```

Anything with a `default` flag would be overwritten by any variable declared inside of the our overrides.

**Comment by mfouquet** [comment]
RE: Underscores. I think the copy/pasting is the biggest thing they have in their favor. Another is that they make it easier to spot what's a variable. My level of care on this one is pretty low though so I'm down with the traditional hyphens if you feel that's the way to go.

Default flag makes sense to me now - thanks for explaining. I really like that approach.

**Comment by gcstaublin** [comment]
Closing.

In a 2-1 beatdown. @mfouquet and @nick-adams imposed the tyranny of underscore naming.
