### ISSUE TITLE
SCSS Authoring

### ISSUE THREAD

**Issue by gcstaublin** [gcstaublin/pregame#8]
How do we want to do this.

#### Option 1 

Pro: Saves typing and is more DRY from an authoring point of view.
Con: However, can make searching a little more difficult. If we do our job and make small, discrete files this might not be an issue.
Note: The nesting you see here, does not create nested CSS.

```
// Button
// --------------------------------------------
.btn {
  &--group { }

  &--block {
    text-align: center;
    display: block;
    width: 100%;
  }

  &--default { @include button($ko-gray--light); }
  &--white { @include button($ko-white); }
  &-primary { @include button($ko-orange); }
  &--danger { @include button($ko-red); }
  &--confirmation { }

  &--cancel {
    @include button(transparent);
    color: $ko-orange;
    background-image: none;
    &:hover { text-decoration: underline; }
  }
} // btn

```

#### Option 2 

```
// Button
// --------------------------------------------

.btn--default { @include button($ko-gray--light); }
.btn--white { @include button($ko-white); }
.btn--primary { @include button($ko-orange); }
.btn--danger { @include button($ko-red); }

.btn__group { }


```

**Comment by gcstaublin** [comment]
As an author, I prefer Option 1. 

However, in terms of clarity, Option 2 might makes the most sense.

**Comment by mfouquet** [comment]
I agree that as an author I prefer Option 1. 

From a less-seasoned view, it might seem like we're saying that nesting is A-OK which makes me gravitate towards Option 2 a bit.

**Comment by gcstaublin** [comment]
Absolutely. 

Honestly, it took me awhile to adopt the authoring style of Option 1, as I thought it would output nested CSS. :shame:

I'm going to call this resolved and close it.

Anyone who wants can re-open and opine, as needed.
